### ISSUE TITLE
"TypeError: source.buffer is not a function" after update from 7.0.0 to 7.1.0 and when use with `webpack-stats-plugin`

### ISSUE THREAD

**Issue by someden** [webpack-contrib/compression-webpack-plugin#236]
There is some error on build after update from 7.0.0 to 7.1.0 and if use `compression-webpack-plugin` with `webpack-stats-plugin`

Error when run `yarn build`:
```
HookWebpackError: source.buffer is not a function
    at makeWebpackError (/my-app/node_modules/webpack/lib/HookWebpackError.js:49:9)
    at /my-app/node_modules/webpack/lib/Compilation.js:2091:11
    at eval (eval at create (/my-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- inner error --
TypeError: source.buffer is not a function
    at /my-app/node_modules/compression-webpack-plugin/dist/index.js:148:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async CompressionPlugin.compress (/my-app/node_modules/compression-webpack-plugin/dist/index.js:103:30)
caused by plugins in Compilation.hooks.processAssets
TypeError: source.buffer is not a function
    at /my-app/node_modules/compression-webpack-plugin/dist/index.js:148:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async CompressionPlugin.compress (/my-app/node_modules/compression-webpack-plugin/dist/index.js:103:30)
error Command failed with exit code 2.
```

Simple config to reproduce:
```js
// webpack.config.js

const path = require('path')
const CompressionPlugin = require('compression-webpack-plugin')
const { StatsWriterPlugin } = require('webpack-stats-plugin')

module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
  },
  plugins: [
    new StatsWriterPlugin(),
    new CompressionPlugin(),

    // Order doesn't matter
    // I've tried with `CompressionPlugin` before `StatsWriterPlugin` too
  ],
}
```

package.json:
```json
{
  "name": "my-app",
  "version": "1.0.0",
  "scripts": {
    "build": "webpack"
  },
  "license": "ISC",
  "dependencies": {
    "compression-webpack-plugin": "^7.1.0",
    "webpack": "^5.11.0",
    "webpack-cli": "^4.2.0",
    "webpack-stats-plugin": "^1.0.2"
  }
}
```

**Comment by alexander-akait** [comment]
Reported https://github.com/FormidableLabs/webpack-stats-plugin/issues/65

**Comment by alexander-akait** [comment]
I will fix it on our side for compatibility reasons

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack-contrib/compression-webpack-plugin/releases/tag/v7.1.1
